server:
  port: 8001

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://discovery-service:8761/eureka/

spring:
  application:
    name: taxi-gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalTrackerFilter
          args:
            baseMessage: Spring Cloud Gateway Global Tracker Filter
            preLogger: true
            postLogger: true
      routes:
        - id: taxi-user-service
          uri: lb://TAXI-USER-SERVICE
          predicates:
            - Path=/taxi-user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/taxi-user-service/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: taxi-user-service
                fallbackuri: forward:/fallback/user
#        - id: bankbook-service-provide
#          uri: lb://BANKBOOK-SERVICE
#          predicates:
#            - Path=/bankbook-service/provide/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/bankbook-service/(?<segment>.*), /$\{segment}
#            - name: CircuitBreaker
#              args:
#                name: bankbook-service
#                fallbackuri: forward:/fallback/bankbook
#        - id: bankbook-service-other
#          uri: lb://BANKBOOK-SERVICE
#          predicates:
#            - Path=/bankbook-service/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/bankbook-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter
#            - name: CircuitBreaker
#              args:
#                name: bankbook-service
#                fallbackuri: forward:/fallback/bankbook

management:
  endpoints:
    web:
      exposure:
        include: health, info

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa